export const airdropRequirements = [
  { type: 'Wallet-Holding Airdrop', requirement: 'Hold a specific token or NFT at a snapshot.' },
  { type: 'Transaction-Based', requirement: 'Make transactions, swaps, bridges, or transfers.' },
  { type: 'Trading-Based', requirement: 'Trade a minimum volume or number of times.' },
  { type: 'Liquidity Provider (LP)', requirement: 'Provide liquidity to a DEX or pool.' },
  { type: 'Staking-Based', requirement: 'Stake tokens for a required period or amount.' },
  { type: 'Bridging-Based', requirement: 'Bridge assets between chains.' },
  { type: 'DeFi Usage', requirement: 'Lend, borrow, swap, provide liquidity, or use protocols.' },
  { type: 'NFT-Based', requirement: 'Mint, hold, trade, or use specific NFTs.' },
  { type: 'Testnet Airdrop', requirement: 'Complete testnet transactions or interactions.' },
  { type: 'Mainnet User', requirement: 'Use a protocol after its mainnet launch.' },
  { type: 'Social Task', requirement: 'Follow, repost, or join Telegram or Discord.' },
  { type: 'Referral Airdrop', requirement: 'Invite users or generate referrals.' },
  { type: 'Quest-Based', requirement: 'Complete predefined quests or tasks.' },
  { type: 'Discord-Based', requirement: 'Join a server, verify, obtain roles, or participate.' },
  { type: 'Telegram-Based', requirement: 'Join a channel or group and complete bot tasks.' },
  { type: 'Governance-Based', requirement: 'Vote, delegate, or participate in governance.' },
  { type: 'Developer/Builder', requirement: 'Deploy contracts, build apps, or contribute code.' },
  { type: 'Contribution-Based', requirement: 'Contribute documentation, translations, support, or content.' },
  { type: 'Early-User Airdrop', requirement: 'Be an early user before a specific cutoff.' },
  { type: 'Retroactive Airdrop', requirement: 'Qualify through historical protocol activity.' },
  { type: 'NFT/Token Holder Snapshot', requirement: 'Hold a qualifying asset at a specific block or time.' },
  { type: 'Ecosystem Airdrop', requirement: 'Use multiple applications within an ecosystem.' },
  { type: 'Referral + Activity', requirement: 'Refer users and complete activity requirements.' },
  { type: 'Points-Based', requirement: 'Earn points through campaign activities.' },
  { type: 'Tier-Based', requirement: 'Meet requirements that determine eligibility or reward tier.' },
  { type: 'Proof-of-Activity', requirement: 'Demonstrate meaningful on-chain activity.' },
  { type: 'Liquidity/Volume Tier', requirement: 'Reach a liquidity or trading-volume threshold.' },
  { type: 'Community/Role-Based', requirement: 'Obtain qualifying Discord or community roles.' },
  { type: 'Content Creator', requirement: 'Create content, tutorials, videos, or posts.' },
  { type: 'Hybrid Airdrop', requirement: 'Complete a combination of multiple requirement types.' },
];